// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnN8Vn9HLnl7POPkJLD3Bv84pgpCzxUbw',
    appId: '1:342099602408:web:7b0e29be3898a15b3cd25d',
    messagingSenderId: '342099602408',
    projectId: 'marriage-bureau-backend',
    authDomain: 'marriage-bureau-backend.firebaseapp.com',
    storageBucket: 'marriage-bureau-backend.appspot.com',
    measurementId: 'G-1KFKCBTTD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI8Ng2QDXwwSTZ1y6F4k9mgnxgAo6lGUY',
    appId: '1:342099602408:android:aead3036840923773cd25d',
    messagingSenderId: '342099602408',
    projectId: 'marriage-bureau-backend',
    storageBucket: 'marriage-bureau-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArnxre9_KijYIukhpJarj5oBrwyYz5nFU',
    appId: '1:342099602408:ios:3476eedbc49cc0183cd25d',
    messagingSenderId: '342099602408',
    projectId: 'marriage-bureau-backend',
    storageBucket: 'marriage-bureau-backend.appspot.com',
    iosBundleId: 'com.example.marriageBureauFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArnxre9_KijYIukhpJarj5oBrwyYz5nFU',
    appId: '1:342099602408:ios:3476eedbc49cc0183cd25d',
    messagingSenderId: '342099602408',
    projectId: 'marriage-bureau-backend',
    storageBucket: 'marriage-bureau-backend.appspot.com',
    iosBundleId: 'com.example.marriageBureauFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnN8Vn9HLnl7POPkJLD3Bv84pgpCzxUbw',
    appId: '1:342099602408:web:ab0aedcd98ea78b63cd25d',
    messagingSenderId: '342099602408',
    projectId: 'marriage-bureau-backend',
    authDomain: 'marriage-bureau-backend.firebaseapp.com',
    storageBucket: 'marriage-bureau-backend.appspot.com',
    measurementId: 'G-YRGMMLJL3R',
  );
}
